#!/bin/sh

# Set these paths appropriately

BIN=/home/pzeroual/5A/REPCONN/TreeTagger/bin
CMD=/home/pzeroual/5A/REPCONN/TreeTagger/cmd
LIB=/home/pzeroual/5A/REPCONN/TreeTagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovak-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
