#!/bin/sh

# Set these paths appropriately

BIN=/home/pzeroual/5A/REPCONN/TreeTagger/bin
CMD=/home/pzeroual/5A/REPCONN/TreeTagger/cmd
LIB=/home/pzeroual/5A/REPCONN/TreeTagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/swahili-abbreviations
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
